## Iris Flower Classification using ANN (TensorFlow/Keras)

In [66]:
!pip install tensorflow

### step 1: import libraries

In [67]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model

# Save model and scaler
import joblib

### step 2 :load dataset

In [68]:
iris=load_iris()
X=iris.data
Y=iris.target

In [69]:
# create dataframe
df=pd.DataFrame(X,columns=iris.feature_names)

In [70]:
# add  target column
df["Target"]=Y

In [71]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


### step 3: preprocessing

In [72]:
df.shape

(150, 5)

In [73]:
print(df.isnull().sum())

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Target               0
dtype: int64


In [74]:
df.duplicated().sum()

np.int64(1)

In [75]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB
None


### step 4: separate input and output

In [76]:
x=df.drop("Target",axis=1)
y=df["Target"]

### step 5: label encoding & one-hot encoding 

In [77]:
# Label encoding
le=LabelEncoder()
y=le.fit_transform(y)
# one-hot encoding 
y_encoded=to_categorical(y)
print(y_encoded[:5])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


### step6:normalize features

In [78]:
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
print(x_scaled[:5])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


### step 7:train_split_test

In [79]:
x_train,x_test,y_train,y_test=train_test_split(
    x_scaled,
    y_encoded,
    test_size=0.2,
    random_state=42
)
print(x_train.shape)
print(x_test.shape)

(120, 4)
(30, 4)


### step 8:build the model

In [80]:
model=Sequential()
# hidden layer 1
model.add(Dense(10,input_shape=(4,),activation="relu"))

# hidden layer 2
model.add(Dense(8,activation="relu"))

# output layer
model.add(Dense(3,activation="softmax"))

C:\Users\hp\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### step 9:compile the model

In [81]:
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

### step 10 :train the model

In [82]:
history=model.fit(
    x_train,
    y_train,
    epochs=50,
    batch_size=8,
    validation_split=0.2
)

Epoch 1/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.3438 - loss: 1.4598 - val_accuracy: 0.2917 - val_loss: 1.3366
Epoch 2/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3438 - loss: 1.3668 - val_accuracy: 0.2917 - val_loss: 1.2495
Epoch 3/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3333 - loss: 1.2832 - val_accuracy: 0.2917 - val_loss: 1.1783
Epoch 4/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3542 - loss: 1.2079 - val_accuracy: 0.2917 - val_loss: 1.1084
Epoch 5/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3333 - loss: 1.1445 - val_accuracy: 0.2083 - val_loss: 1.0520
Epoch 6/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3021 - loss: 1.0927 - val_accuracy: 0.2083 - val_loss: 0.9981
Epoch 7/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2917 - loss: 1.0463 - val_accuracy: 0.3750 - val_loss: 0.9523
Epoch 8/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3854 - loss: 1.0041 - val_accuracy: 0.5000 - v

### step 11: evaluate the model

In [83]:
loss,accuracy =model.evaluate(x_test,y_test)

print("loss:",loss)
print("accuracy:",accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step - accuracy: 0.9667 - loss: 0.1875
loss: 0.18753916025161743
accuracy: 0.9666666388511658


### step12:prediction

In [84]:
y_pred=model.predict(x_test)

# convert predicted values
y_pred_classes=np.argmax(y_pred,axis=1)

# convert actual values
y_test_classes=np.argmax(y_pred,axis=1)

print("predicted values:")
print(y_pred_classes[:10])

print("Actual values:")
print(y_test_classes[:10])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
predicted values:
[1 0 2 1 2 0 1 2 1 1]
Actual values:
[1 0 2 1 2 0 1 2 1 1]


### step 13:accuracy score

In [85]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test_classes,y_pred_classes)
print("Accuracy score:",acc)

Accuracy score: 1.0


### step 14:classification report

In [86]:
from sklearn.metrics import classification_report
print(classification_report(y_test_classes,y_pred_classes))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00        12

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



### Step 15: Save Model and Scaler

In [87]:
# Save ANN Model
model.save("iris_ann_model.keras")
# Save Scaler
joblib.dump(scaler, "iris_scaler.pkl")
print("Model and Scaler Saved Successfully")

Model and Scaler Saved Successfully


### Step 16: Load Saved Model and Scaler

In [88]:
loaded_model = load_model("iris_ann_model.keras")

loaded_scaler = joblib.load("iris_scaler.pkl")

### Step 17: Test with Unseen Sample

In [89]:
# sample flower
unseen_sample = np.array([
    [5.1, 3.5, 1.4, 0.2]
])

In [90]:
# scale data
unseen_scaled = loaded_scaler.transform(unseen_sample)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [92]:
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_iris

iris = load_iris()

species_names = iris.target_names

label_encoder = LabelEncoder()
label_encoder.fit(species_names)

LabelEncoder()

In [93]:
# Predict
prediction = loaded_model.predict(unseen_scaled)

predicted_class = np.argmax(prediction)

predicted_species = label_encoder.inverse_transform(
    [predicted_class]
)

print("Predicted Flower Species:",
      predicted_species[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
Predicted Flower Species: setosa


### Conclusion

The ANN model was successfully developed to classify Iris flowers into Setosa, Versicolor, and Virginica. After preprocessing, feature scaling, and training with TensorFlow/Keras, the model achieved high classification accuracy. The results demonstrate that Artificial Neural Networks are effective for multiclass classification tasks and can accurately predict flower species from unseen data.